<?php
$con = mysqli_connect("localhost", "root", "", "hill");


if (isset($_POST['submit'])) {

    $name = $_POST['name'];
    $email = $_POST['email'];
    $PhoneNumber = $_POST['PhoneNumber'];
    $Gender = $_POST['Gender'];
    $birthDate = $_POST['birthDate'];
    $MaritalStatus = $_POST['MaritalStatus'];
    $countryRegion = $_POST['countryRegion'];
    $areyouWatchman = $_POST['areyouWatchman'];
    $Denomination = $_POST['Denomination'];
    $diocese = $_POST['diocese'];
    $parish = $_POST['parish'];
    $AreYouaWorker = $_POST['AreYouaWorker'];
    $Ministrydepartment = $_POST['Ministrydepartment'];
    $specify = $_POST['specify'];
    $AcademicStatus = $_POST['AcademicStatus'];
    $Qualification = $_POST['Qualification'];
    $specify2 = $_POST['specify2'];
    $LEVEL = $_POST['LEVEL'];
    $CLASS = $_POST['CLASS'];
    $campus = $_POST['campus'];
    $hostel = $_POST['hostel'];

    $insert = mysqli_query($con, "INSERT INTO user(name,email,PhoneNumber,gender,birthDate,MaritalStatus,countryRegion,areyouWatchman,Denomination,diocese,parish,AreYouaWorker,Ministrydepartment,specify,AcademicStatus,Qualification,specify2,LEVEL,CLASS,campus,hostel) VALUES('$name','$email','$PhoneNumber','$Gender','$birthDate','$MaritalStatus','$countryRegion','$areyouWatchman','$Denomination','$diocese','$parish','$AreYouaWorker','$Ministrydepartment','$specify','$AcademicStatus','$Qualification','$specify2','$LEVEL','$CLASS','$campus','$hostel')");
// close for now
    // if ($insert) {
      //  echo "<h1>Submitted Successfully</h1>";
    //} else {
      //  echo "Error" . $insert . "</br>" . $con->error;
    //}
}

?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="profile" href="http://gmpg.org/xfn/11">

<title>Watchman Catholic Charismatic Campus Fellowship</title>
<script type="text/javascript">var ajaxurl = "https://www.watchmancampus.org/office/admin-ajax.php",ap_nonce 	= "6a0a1b368b",apTemplateUrl = "https://www.watchmancampus.org/wp-content/plugins/anspress-question-answer/templates/js-template";apQuestionID = "0";aplang = {"loading":"Loading..","sending":"Sending request","file_size_error":"File size is bigger than 0.48 MB","attached_max":"You have already attached maximum numbers of allowed attachments","commented":"commented","comment":"Comment","cancel":"Cancel","update":"Update","your_comment":"Write your comment...","notifications":"Notifications","mark_all_seen":"Mark all as seen","search":"Search","no_permission_comments":"Sorry, you don't have permission to read comments."};disable_q_suggestion = "";</script><meta name='robots' content='max-image-preview:large' />

<!-- Open Graph Meta Tags generated by Blog2Social 699 - https://www.blog2social.com -->
<meta property="og:title" content=""/>
<meta property="og:description" content=""/>
<meta property="og:url" content="https://www.watchmancampus.org/5926-2/"/>
<meta property="og:type" content="article"/>
<meta property="og:article:published_time" content="2022-07-09 19:49:57"/>
<meta property="og:article:modified_time" content="2022-07-09 19:49:57"/>
<!-- Open Graph Meta Tags generated by Blog2Social 699 - https://www.blog2social.com -->

<!-- Twitter Card generated by Blog2Social 699 - https://www.blog2social.com -->
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content=""/>
<meta name="twitter:description" content=""/>
<!-- Twitter Card generated by Blog2Social 699 - https://www.blog2social.com -->
<meta name="author" content="David Chinemelu"/>
<link rel='dns-prefetch' href='http://fonts.googleapis.com/' />
<link rel='dns-prefetch' href='http://s.w.org/' />
<link rel="alternate" type="application/rss+xml" title="Watchman Catholic Charismatic Campus Fellowship &raquo; Feed" href="https://www.watchmancampus.org/feed/" />
<link rel="alternate" type="application/rss+xml" title="Watchman Catholic Charismatic Campus Fellowship &raquo; Comments Feed" href="https://www.watchmancampus.org/comments/feed/" />
		<!-- This site uses the Google Analytics by MonsterInsights plugin v8.5.0 - Using Analytics tracking - https://www.monsterinsights.com/ -->
		<!-- Note: MonsterInsights is not currently configured on this site. The site owner needs to authenticate with Google Analytics in the MonsterInsights settings panel. -->
					<!-- No UA code set -->
				<!-- / Google Analytics by MonsterInsights -->
		<script type="text/javascript">
window._wpemojiSettings = {"baseUrl":"https:\/\/s.w.org\/images\/core\/emoji\/14.0.0\/72x72\/","ext":".png","svgUrl":"https:\/\/s.w.org\/images\/core\/emoji\/14.0.0\/svg\/","svgExt":".svg","source":{"concatemoji":"https:\/\/www.watchmancampus.org\/wp-includes\/js\/wp-emoji-release.min.js?ver=6.0"}};
/*! This file is auto-generated */
!function(e,a,t){var n,r,o,i=a.createElement("canvas"),p=i.getContext&&i.getContext("2d");function s(e,t){var a=String.fromCharCode,e=(p.clearRect(0,0,i.width,i.height),p.fillText(a.apply(this,e),0,0),i.toDataURL());return p.clearRect(0,0,i.width,i.height),p.fillText(a.apply(this,t),0,0),e===i.toDataURL()}function c(e){var t=a.createElement("script");t.src=e,t.defer=t.type="text/javascript",a.getElementsByTagName("head")[0].appendChild(t)}for(o=Array("flag","emoji"),t.supports={everything:!0,everythingExceptFlag:!0},r=0;r<o.length;r++)t.supports[o[r]]=function(e){if(!p||!p.fillText)return!1;switch(p.textBaseline="top",p.font="600 32px Arial",e){case"flag":return s([127987,65039,8205,9895,65039],[127987,65039,8203,9895,65039])?!1:!s([55356,56826,55356,56819],[55356,56826,8203,55356,56819])&&!s([55356,57332,56128,56423,56128,56418,56128,56421,56128,56430,56128,56423,56128,56447],[55356,57332,8203,56128,56423,8203,56128,56418,8203,56128,56421,8203,56128,56430,8203,56128,56423,8203,56128,56447]);case"emoji":return!s([129777,127995,8205,129778,127999],[129777,127995,8203,129778,127999])}return!1}(o[r]),t.supports.everything=t.supports.everything&&t.supports[o[r]],"flag"!==o[r]&&(t.supports.everythingExceptFlag=t.supports.everythingExceptFlag&&t.supports[o[r]]);t.supports.everythingExceptFlag=t.supports.everythingExceptFlag&&!t.supports.flag,t.DOMReady=!1,t.readyCallback=function(){t.DOMReady=!0},t.supports.everything||(n=function(){t.readyCallback()},a.addEventListener?(a.addEventListener("DOMContentLoaded",n,!1),e.addEventListener("load",n,!1)):(e.attachEvent("onload",n),a.attachEvent("onreadystatechange",function(){"complete"===a.readyState&&t.readyCallback()})),(e=t.source||{}).concatemoji?c(e.concatemoji):e.wpemoji&&e.twemoji&&(c(e.twemoji),c(e.wpemoji)))}(window,document,window._wpemojiSettings);
</script>
<style type="text/css">
img.wp-smiley,
img.emoji {
	display: inline !important;
	border: none !important;
	box-shadow: none !important;
	height: 1em !important;
	width: 1em !important;
	margin: 0 0.07em !important;
	vertical-align: -0.1em !important;
	background: none !important;
	padding: 0 !important;
}
</style>
	<link rel='stylesheet' id='cf7s-framework-normalize-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/contact-form-7-skins/css/framework/cf7s-normalize91ee.css?ver=2.5.3' type='text/css' media='all' />
<link rel='stylesheet' id='cf7s-framework-default-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/contact-form-7-skins/css/framework/cf7s-default91ee.css?ver=2.5.3' type='text/css' media='all' />
<link rel='stylesheet' id='cf7s-seaspray-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/contact-form-7-skins/skins/styles/seaspray/seaspray91ee.css?ver=2.5.3' type='text/css' media='all' />
<link rel='stylesheet' id='cf7s-pina-colada-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/contact-form-7-skins/skins/styles/pina-colada/pina-colada91ee.css?ver=2.5.3' type='text/css' media='all' />
<link rel='stylesheet' id='anspress-fonts-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/anspress-question-answer/templates/css/fontsb2f9.css?ver=4.3.0' type='text/css' media='all' />
<link rel='stylesheet' id='anspress-main-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/anspress-question-answer/templates/css/mainb2f9.css?ver=4.3.0' type='text/css' media='all' />
<style id='anspress-main-inline-css' type='text/css'>

		#anspress .ap-q-cells{
				margin-left: 60px;
		}
		#anspress .ap-a-cells{
				margin-left: 60px;
		}
</style>
<link rel='stylesheet' id='ap-overrides-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/anspress-question-answer/templates/css/overridesac5b.css?v=4.3.0&amp;ver=4.3.0' type='text/css' media='all' />
<link rel='stylesheet' id='wp-block-library-css'  href='wp-includes/css/dist/block-library/style.minf049.css?ver=6.0' type='text/css' media='all' />
<link rel='stylesheet' id='wc-blocks-vendors-style-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/woocommerce/packages/woocommerce-blocks/build/wc-blocks-vendors-stylecb57.css?ver=7.2.2' type='text/css' media='all' />
<link rel='stylesheet' id='wc-blocks-style-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/woocommerce/packages/woocommerce-blocks/build/wc-blocks-stylecb57.css?ver=7.2.2' type='text/css' media='all' />
<link rel='stylesheet' id='embedpress_blocks-cgb-style-css-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/embedpress/Gutenberg/dist/blocks.style.buildd284.css?ver=1651053576' type='text/css' media='all' />
<link rel='stylesheet' id='ht-contactform-block-style-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/ht-contactform/blocks/src/assets/css/style-indexcfa9.css?ver=1.1.2' type='text/css' media='all' />
<style id='global-styles-inline-css' type='text/css'>
body{--wp--preset--color--black: #000000;--wp--preset--color--cyan-bluish-gray: #abb8c3;--wp--preset--color--white: #ffffff;--wp--preset--color--pale-pink: #f78da7;--wp--preset--color--vivid-red: #cf2e2e;--wp--preset--color--luminous-vivid-orange: #ff6900;--wp--preset--color--luminous-vivid-amber: #fcb900;--wp--preset--color--light-green-cyan: #7bdcb5;--wp--preset--color--vivid-green-cyan: #00d084;--wp--preset--color--pale-cyan-blue: #8ed1fc;--wp--preset--color--vivid-cyan-blue: #0693e3;--wp--preset--color--vivid-purple: #9b51e0;--wp--preset--gradient--vivid-cyan-blue-to-vivid-purple: linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%);--wp--preset--gradient--light-green-cyan-to-vivid-green-cyan: linear-gradient(135deg,rgb(122,220,180) 0%,rgb(0,208,130) 100%);--wp--preset--gradient--luminous-vivid-amber-to-luminous-vivid-orange: linear-gradient(135deg,rgba(252,185,0,1) 0%,rgba(255,105,0,1) 100%);--wp--preset--gradient--luminous-vivid-orange-to-vivid-red: linear-gradient(135deg,rgba(255,105,0,1) 0%,rgb(207,46,46) 100%);--wp--preset--gradient--very-light-gray-to-cyan-bluish-gray: linear-gradient(135deg,rgb(238,238,238) 0%,rgb(169,184,195) 100%);--wp--preset--gradient--cool-to-warm-spectrum: linear-gradient(135deg,rgb(74,234,220) 0%,rgb(151,120,209) 20%,rgb(207,42,186) 40%,rgb(238,44,130) 60%,rgb(251,105,98) 80%,rgb(254,248,76) 100%);--wp--preset--gradient--blush-light-purple: linear-gradient(135deg,rgb(255,206,236) 0%,rgb(152,150,240) 100%);--wp--preset--gradient--blush-bordeaux: linear-gradient(135deg,rgb(254,205,165) 0%,rgb(254,45,45) 50%,rgb(107,0,62) 100%);--wp--preset--gradient--luminous-dusk: linear-gradient(135deg,rgb(255,203,112) 0%,rgb(199,81,192) 50%,rgb(65,88,208) 100%);--wp--preset--gradient--pale-ocean: linear-gradient(135deg,rgb(255,245,203) 0%,rgb(182,227,212) 50%,rgb(51,167,181) 100%);--wp--preset--gradient--electric-grass: linear-gradient(135deg,rgb(202,248,128) 0%,rgb(113,206,126) 100%);--wp--preset--gradient--midnight: linear-gradient(135deg,rgb(2,3,129) 0%,rgb(40,116,252) 100%);--wp--preset--duotone--dark-grayscale: url('#wp-duotone-dark-grayscale');--wp--preset--duotone--grayscale: url('#wp-duotone-grayscale');--wp--preset--duotone--purple-yellow: url('#wp-duotone-purple-yellow');--wp--preset--duotone--blue-red: url('#wp-duotone-blue-red');--wp--preset--duotone--midnight: url('#wp-duotone-midnight');--wp--preset--duotone--magenta-yellow: url('#wp-duotone-magenta-yellow');--wp--preset--duotone--purple-green: url('#wp-duotone-purple-green');--wp--preset--duotone--blue-orange: url('#wp-duotone-blue-orange');--wp--preset--font-size--small: 13px;--wp--preset--font-size--medium: 20px;--wp--preset--font-size--large: 36px;--wp--preset--font-size--x-large: 42px;}.has-black-color{color: var(--wp--preset--color--black) !important;}.has-cyan-bluish-gray-color{color: var(--wp--preset--color--cyan-bluish-gray) !important;}.has-white-color{color: var(--wp--preset--color--white) !important;}.has-pale-pink-color{color: var(--wp--preset--color--pale-pink) !important;}.has-vivid-red-color{color: var(--wp--preset--color--vivid-red) !important;}.has-luminous-vivid-orange-color{color: var(--wp--preset--color--luminous-vivid-orange) !important;}.has-luminous-vivid-amber-color{color: var(--wp--preset--color--luminous-vivid-amber) !important;}.has-light-green-cyan-color{color: var(--wp--preset--color--light-green-cyan) !important;}.has-vivid-green-cyan-color{color: var(--wp--preset--color--vivid-green-cyan) !important;}.has-pale-cyan-blue-color{color: var(--wp--preset--color--pale-cyan-blue) !important;}.has-vivid-cyan-blue-color{color: var(--wp--preset--color--vivid-cyan-blue) !important;}.has-vivid-purple-color{color: var(--wp--preset--color--vivid-purple) !important;}.has-black-background-color{background-color: var(--wp--preset--color--black) !important;}.has-cyan-bluish-gray-background-color{background-color: var(--wp--preset--color--cyan-bluish-gray) !important;}.has-white-background-color{background-color: var(--wp--preset--color--white) !important;}.has-pale-pink-background-color{background-color: var(--wp--preset--color--pale-pink) !important;}.has-vivid-red-background-color{background-color: var(--wp--preset--color--vivid-red) !important;}.has-luminous-vivid-orange-background-color{background-color: var(--wp--preset--color--luminous-vivid-orange) !important;}.has-luminous-vivid-amber-background-color{background-color: var(--wp--preset--color--luminous-vivid-amber) !important;}.has-light-green-cyan-background-color{background-color: var(--wp--preset--color--light-green-cyan) !important;}.has-vivid-green-cyan-background-color{background-color: var(--wp--preset--color--vivid-green-cyan) !important;}.has-pale-cyan-blue-background-color{background-color: var(--wp--preset--color--pale-cyan-blue) !important;}.has-vivid-cyan-blue-background-color{background-color: var(--wp--preset--color--vivid-cyan-blue) !important;}.has-vivid-purple-background-color{background-color: var(--wp--preset--color--vivid-purple) !important;}.has-black-border-color{border-color: var(--wp--preset--color--black) !important;}.has-cyan-bluish-gray-border-color{border-color: var(--wp--preset--color--cyan-bluish-gray) !important;}.has-white-border-color{border-color: var(--wp--preset--color--white) !important;}.has-pale-pink-border-color{border-color: var(--wp--preset--color--pale-pink) !important;}.has-vivid-red-border-color{border-color: var(--wp--preset--color--vivid-red) !important;}.has-luminous-vivid-orange-border-color{border-color: var(--wp--preset--color--luminous-vivid-orange) !important;}.has-luminous-vivid-amber-border-color{border-color: var(--wp--preset--color--luminous-vivid-amber) !important;}.has-light-green-cyan-border-color{border-color: var(--wp--preset--color--light-green-cyan) !important;}.has-vivid-green-cyan-border-color{border-color: var(--wp--preset--color--vivid-green-cyan) !important;}.has-pale-cyan-blue-border-color{border-color: var(--wp--preset--color--pale-cyan-blue) !important;}.has-vivid-cyan-blue-border-color{border-color: var(--wp--preset--color--vivid-cyan-blue) !important;}.has-vivid-purple-border-color{border-color: var(--wp--preset--color--vivid-purple) !important;}.has-vivid-cyan-blue-to-vivid-purple-gradient-background{background: var(--wp--preset--gradient--vivid-cyan-blue-to-vivid-purple) !important;}.has-light-green-cyan-to-vivid-green-cyan-gradient-background{background: var(--wp--preset--gradient--light-green-cyan-to-vivid-green-cyan) !important;}.has-luminous-vivid-amber-to-luminous-vivid-orange-gradient-background{background: var(--wp--preset--gradient--luminous-vivid-amber-to-luminous-vivid-orange) !important;}.has-luminous-vivid-orange-to-vivid-red-gradient-background{background: var(--wp--preset--gradient--luminous-vivid-orange-to-vivid-red) !important;}.has-very-light-gray-to-cyan-bluish-gray-gradient-background{background: var(--wp--preset--gradient--very-light-gray-to-cyan-bluish-gray) !important;}.has-cool-to-warm-spectrum-gradient-background{background: var(--wp--preset--gradient--cool-to-warm-spectrum) !important;}.has-blush-light-purple-gradient-background{background: var(--wp--preset--gradient--blush-light-purple) !important;}.has-blush-bordeaux-gradient-background{background: var(--wp--preset--gradient--blush-bordeaux) !important;}.has-luminous-dusk-gradient-background{background: var(--wp--preset--gradient--luminous-dusk) !important;}.has-pale-ocean-gradient-background{background: var(--wp--preset--gradient--pale-ocean) !important;}.has-electric-grass-gradient-background{background: var(--wp--preset--gradient--electric-grass) !important;}.has-midnight-gradient-background{background: var(--wp--preset--gradient--midnight) !important;}.has-small-font-size{font-size: var(--wp--preset--font-size--small) !important;}.has-medium-font-size{font-size: var(--wp--preset--font-size--medium) !important;}.has-large-font-size{font-size: var(--wp--preset--font-size--large) !important;}.has-x-large-font-size{font-size: var(--wp--preset--font-size--x-large) !important;}
</style>
<link rel='stylesheet' id='af-fontawesome-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/asgaros-forum/libs/fontawesome/css/all.min001e.css?ver=2.0.0' type='text/css' media='all' />
<link rel='stylesheet' id='af-fontawesome-compat-v4-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/asgaros-forum/libs/fontawesome/css/v4-shims.min001e.css?ver=2.0.0' type='text/css' media='all' />
<link rel='stylesheet' id='af-widgets-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/asgaros-forum/skin/widgets001e.css?ver=2.0.0' type='text/css' media='all' />
<link rel='stylesheet' id='contact-form-7-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/contact-form-7/includes/css/styles04dd.css?ver=5.5.6.1' type='text/css' media='all' />
<link rel='stylesheet' id='wpcdt-public-css-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/countdown-timer-ultimate/assets/css/wpcdt-publica7f4.css?ver=2.0.8' type='text/css' media='all' />
<link rel='stylesheet' id='rm_theme_matchmytheme-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/custom-registration-form-builder-with-submission-manager/public/css/theme_rm_matchmytheme189b.css?ver=5.1.5.8' type='text/css' media='all' />
<link rel='stylesheet' id='RegistrationMagic-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/custom-registration-form-builder-with-submission-manager/public/css/style_rm_front_end189b.css?ver=5.1.5.8' type='text/css' media='all' />
<link rel='stylesheet' id='embedpress-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/embedpress/assets/css/embedpressf049.css?ver=6.0' type='text/css' media='all' />
<link rel='stylesheet' id='mptt-style-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/mp-timetable/media/css/style2f91.css?ver=2.4.6' type='text/css' media='all' />
<link rel='stylesheet' id='profilegrid-user-profiles-groups-and-communities-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/profilegrid-user-profiles-groups-and-communities/public/css/profile-magic-public6959.css?ver=4.9.3' type='text/css' media='all' />
<link rel='stylesheet' id='pm-font-awesome-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/profilegrid-user-profiles-groups-and-communities/public/css/font-awesome6959.css?ver=4.9.3' type='text/css' media='all' />
<link rel='stylesheet' id='pg-password-checker-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/profilegrid-user-profiles-groups-and-communities/public/css/pg-password-checker6959.css?ver=4.9.3' type='text/css' media='all' />
<link rel='stylesheet' id='pg-profile-menu-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/profilegrid-user-profiles-groups-and-communities/public/css/pg-profile-menu6959.css?ver=4.9.3' type='text/css' media='all' />
<link rel='stylesheet' id='pg-responsive-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/profilegrid-user-profiles-groups-and-communities/public/css/pg-responsive-public6959.css?ver=4.9.3' type='text/css' media='all' />
<link rel='stylesheet' id='woocommerce-layout-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/woocommerce/assets/css/woocommerce-layoutaec2.css?ver=6.4.1' type='text/css' media='all' />
<link rel='stylesheet' id='woocommerce-smallscreen-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/woocommerce/assets/css/woocommerce-smallscreenaec2.css?ver=6.4.1' type='text/css' media='only screen and (max-width: 768px)' />
<link rel='stylesheet' id='woocommerce-general-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/woocommerce/assets/css/woocommerceaec2.css?ver=6.4.1' type='text/css' media='all' />
<style id='woocommerce-inline-inline-css' type='text/css'>
.woocommerce form .form-row .required { visibility: visible; }
</style>
<link rel='stylesheet' id='cf7-pdf-generation-public-css-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/generate-pdf-using-contact-form-7/assets/css/cf7-pdf-generation-public-min62ea.css?ver=1.2' type='text/css' media='all' />
<link rel='stylesheet' id='bootstrap-min-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/themes/cozipress-pro/assets/css/bootstrap.minf049.css?ver=6.0' type='text/css' media='all' />
<link rel='stylesheet' id='owl-carousel-min-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/themes/cozipress-pro/assets/css/owl.carousel.minf049.css?ver=6.0' type='text/css' media='all' />
<link rel='stylesheet' id='font-awesome-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/elementor/assets/lib/font-awesome/css/font-awesome.min1849.css?ver=4.7.0' type='text/css' media='all' />
<link rel='stylesheet' id='animate-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/themes/cozipress-pro/assets/css/animate.minf049.css?ver=6.0' type='text/css' media='all' />
<link rel='stylesheet' id='magnific-popup-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/themes/cozipress-pro/assets/css/magnific-popup.minf049.css?ver=6.0' type='text/css' media='all' />
<link rel='stylesheet' id='cozipress-editor-style-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/themes/cozipress-pro/assets/css/editor-stylef049.css?ver=6.0' type='text/css' media='all' />
<link rel='stylesheet' id='cozipress-menus-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/themes/cozipress-pro/assets/css/classic-menuf049.css?ver=6.0' type='text/css' media='all' />
<link rel='stylesheet' id='cozipress-widgets-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/themes/cozipress-pro/assets/css/widgetsf049.css?ver=6.0' type='text/css' media='all' />
<link rel='stylesheet' id='cozipress-main-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/themes/cozipress-pro/assets/css/mainf049.css?ver=6.0' type='text/css' media='all' />
<link rel='stylesheet' id='cozipress-woo-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/themes/cozipress-pro/assets/css/woof049.css?ver=6.0' type='text/css' media='all' />
<link rel='stylesheet' id='cozipress-media-query-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/themes/cozipress-pro/assets/css/responsivef049.css?ver=6.0' type='text/css' media='all' />
<link rel='stylesheet' id='cozipress-style-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/themes/cozipress-pro/stylef049.css?ver=6.0' type='text/css' media='all' />
<style id='cozipress-style-inline-css' type='text/css'>
.main-slider {
					    background: rgba(0, 0, 0, 0.55);
				}
.breadcrumb-area { min-height: 73px;} .breadcrumb-area:after {
					background-color: #000000;
					opacity: 0.45;
				}
.site-description { font-size: 12px !important;} @media (max-width:768px) {.site-description { font-size: 12px !important;} } @media (max-width:480px) {.site-description { font-size: 12px !important;} } :root {
								--bs-black:#000000;
								--bs-blue:#0d6efd;
								--bs-indigo:#6610f2;
								--bs-purple:#6f42c1;
								--bs-pink:#d63384;
								--bs-red:#dc221c;
								--bs-orange:#fd7e14;
								--bs-orange-dark:#ee4a34;
								--bs-orange-dark-light:#fae4df;
								--bs-yellow:#ffcc00;
								--bs-green:#28a745;
								--bs-teal:#20c997;
								--bs-cyan:#17a2b8;
								--bs-white:#ffffff;
								--bs-gray:#dedede;
								--bs-gray-light: #f7f7f7;
								--bs-gray-dark:#343a40;
								--bs-primary:#007bff;
								--bs-primary-dark:#025ce2;
								--bs-primary-light: #effffc;
								--bs-primary-shadow:rgb(0 123 255 / 0.5);
								--bs-secondary:#214462;
								--bs-secondary-dark: #1f2120;
								--bs-gray-500: #f2f2f2;
								--bs-gray-500-thumb: #c2c2c2;
								--bs-success:#28a745;
								--bs-info:#17a2b8;
								--bs-warning:#ffc107;
								--bs-danger:#dc3545;
								--bs-light:#f8f9fa;
								--bs-dark:#343a40;
								--bs-gradient:linear-gradient(180deg,rgba(255,255,255,0.15),rgba(255,255,255,0));
								--bs-gradient-image:linear-gradient(180deg,rgba(255,255,255,0.15),rgba(255,255,255,0));
								--bs-shadow: 2px 5px 20px rgba(0, 0, 0, .2);
								--bs-radius: 0.1875rem;
								--bs-theme-radius: 6.25rem;
								--bs-transition: all .35s cubic-bezier(.645,.045,.355,1);
								--bs-transition-slow: all .55s cubic-bezier(.645,.045,.355,1);
								--bs-transition-very-slow: all .75s cubic-bezier(.645,.045,.355,1);
							}.heading-default .badge:after{
								    background-color: rgba(0, 123, 255, .2);
							}
:root {
								--bs-black:#000000;
								--bs-blue:#0d6efd;
								--bs-indigo:#6610f2;
								--bs-purple:#6f42c1;
								--bs-pink:#d63384;
								--bs-red:#dc221c;
								--bs-orange:#fd7e14;
								--bs-orange-dark:#ee4a34;
								--bs-orange-dark-light:#fae4df;
								--bs-yellow:#ffcc00;
								--bs-green:#28a745;
								--bs-teal:#20c997;
								--bs-cyan:#17a2b8;
								--bs-white:#ffffff;
								--bs-gray:#dedede;
								--bs-gray-light: #f7f7f7;
								--bs-gray-dark:#343a40;
								--bs-primary:#c76a1a;
								--bs-primary-dark:#025ce2;
								--bs-primary-light: #effffc;
								--bs-primary-shadow:rgb(0 123 255 / 0.5);
								--bs-secondary:;
								--bs-secondary-dark: #1f2120;
								--bs-gray-500: #f2f2f2;
								--bs-gray-500-thumb: #c2c2c2;
								--bs-success:#28a745;
								--bs-info:#17a2b8;
								--bs-warning:#ffc107;
								--bs-danger:#dc3545;
								--bs-light:#f8f9fa;
								--bs-dark:#343a40;
								--bs-gradient:linear-gradient(180deg,rgba(255,255,255,0.15),rgba(255,255,255,0));
								--bs-gradient-image:linear-gradient(180deg,rgba(255,255,255,0.15),rgba(255,255,255,0));
								--bs-shadow: 2px 5px 20px rgba(0, 0, 0, .2);
								--bs-radius: 0.1875rem;
								--bs-theme-radius: 6.25rem;
								--bs-transition: all .35s cubic-bezier(.645,.045,.355,1);
								--bs-transition-slow: all .55s cubic-bezier(.645,.045,.355,1);
								--bs-transition-very-slow: all .75s cubic-bezier(.645,.045,.355,1);
							}.heading-default .badge:after{
								     background-color: rgba(199, 106, 26, .2);
							}
 body{ 
			font-weight: inherit;
			text-transform: capitalize;
			font-style: inherit;
			text-decoration: inherit;
		} a {text-decoration: inherit;
		}
 h1{ 
				font-family: ;
				font-weight: 700;
				text-transform: inherit;
				font-style: inherit;
				text-decoration: inherit;
			}
 h2{ 
				font-family: ;
				font-weight: 700;
				text-transform: inherit;
				font-style: inherit;
				text-decoration: inherit;
			}
 h3{ 
				font-family: ;
				font-weight: 700;
				text-transform: inherit;
				font-style: inherit;
				text-decoration: inherit;
			}
 h4{ 
				font-family: ;
				font-weight: 700;
				text-transform: inherit;
				font-style: inherit;
				text-decoration: inherit;
			}
 h5{ 
				font-family: ;
				font-weight: 700;
				text-transform: inherit;
				font-style: inherit;
				text-decoration: inherit;
			}
 h6{ 
				font-family: ;
				font-weight: 700;
				text-transform: inherit;
				font-style: inherit;
				text-decoration: inherit;
			}
@media (min-width: 992px) {
							.footer-parallax .cozipress-content {
								position: relative;
								margin-bottom: 181px;
								box-shadow: 0 5px 10px 0 rgb(51 51 51 / 50%);
								z-index: 1;
							}
							.footer-parallax .main-footer {
								position: fixed;
								bottom: 0;
								left: 0;
								width: 100%;
								z-index: 0;
							}
						}

</style>
<link rel='stylesheet' id='cozipress-fonts-css'  href='http://fonts.googleapis.com/css?family=Montserrat%3Aital%2Cwght%400%2C200%3B0%2C300%3B0%2C400%3B0%2C500%3B0%2C600%3B0%2C700%3B0%2C800%3B0%2C900%3B1%2C100%3B1%2C200%3B1%2C300%3B1%2C400%3B1%2C500%3B1%2C600%3B1%2C700%3B1%2C800%3B1%2C900&amp;subset=latin%2Clatin-ext' type='text/css' media='all' />
<link rel='stylesheet' id='tablepress-default-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/tablepress/css/default.mind50e.css?ver=1.14' type='text/css' media='all' />
<link rel='stylesheet' id='dashicons-css'  href='wp-includes/css/dashicons.minf049.css?ver=6.0' type='text/css' media='all' />
<link rel='stylesheet' id='cf7cf-style-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/cf7-conditional-fields/styled63f.css?ver=2.1.5' type='text/css' media='all' />
<link rel='stylesheet' id='um_fonticons_ii-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/ultimate-member/assets/css/um-fonticons-ii95b8.css?ver=2.3.2' type='text/css' media='all' />
<link rel='stylesheet' id='um_fonticons_fa-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/ultimate-member/assets/css/um-fonticons-fa95b8.css?ver=2.3.2' type='text/css' media='all' />
<link rel='stylesheet' id='select2-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/ultimate-member/assets/css/select2/select2.min4819.css?ver=4.0.13' type='text/css' media='all' />
<link rel='stylesheet' id='um_crop-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/ultimate-member/assets/css/um-crop95b8.css?ver=2.3.2' type='text/css' media='all' />
<link rel='stylesheet' id='um_modal-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/ultimate-member/assets/css/um-modal95b8.css?ver=2.3.2' type='text/css' media='all' />
<link rel='stylesheet' id='um_styles-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/ultimate-member/assets/css/um-styles95b8.css?ver=2.3.2' type='text/css' media='all' />
<link rel='stylesheet' id='um_profile-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/ultimate-member/assets/css/um-profile95b8.css?ver=2.3.2' type='text/css' media='all' />
<link rel='stylesheet' id='um_account-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/ultimate-member/assets/css/um-account95b8.css?ver=2.3.2' type='text/css' media='all' />
<link rel='stylesheet' id='um_misc-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/ultimate-member/assets/css/um-misc95b8.css?ver=2.3.2' type='text/css' media='all' />
<link rel='stylesheet' id='um_fileupload-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/ultimate-member/assets/css/um-fileupload95b8.css?ver=2.3.2' type='text/css' media='all' />
<link rel='stylesheet' id='um_datetime-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/ultimate-member/assets/css/pickadate/default95b8.css?ver=2.3.2' type='text/css' media='all' />
<link rel='stylesheet' id='um_datetime_date-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/ultimate-member/assets/css/pickadate/default.date95b8.css?ver=2.3.2' type='text/css' media='all' />
<link rel='stylesheet' id='um_datetime_time-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/ultimate-member/assets/css/pickadate/default.time95b8.css?ver=2.3.2' type='text/css' media='all' />
<link rel='stylesheet' id='um_raty-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/ultimate-member/assets/css/um-raty95b8.css?ver=2.3.2' type='text/css' media='all' />
<link rel='stylesheet' id='um_scrollbar-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/ultimate-member/assets/css/simplebar95b8.css?ver=2.3.2' type='text/css' media='all' />
<link rel='stylesheet' id='um_tipsy-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/ultimate-member/assets/css/um-tipsy95b8.css?ver=2.3.2' type='text/css' media='all' />
<link rel='stylesheet' id='um_responsive-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/ultimate-member/assets/css/um-responsive95b8.css?ver=2.3.2' type='text/css' media='all' />
<link rel='stylesheet' id='um_default_css-css'  href='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/ultimate-member/assets/css/um-old-default95b8.css?ver=2.3.2' type='text/css' media='all' />
<!--n2css--><script type='text/javascript' src='wp-includes/js/jquery/jquery.minaf6c.js?ver=3.6.0' id='jquery-core-js'></script>
<script type='text/javascript' src='wp-includes/js/jquery/jquery-migrate.mind617.js?ver=3.3.2' id='jquery-migrate-js'></script>
<script type='text/javascript' src='wp-includes/js/jquery/ui/core.min0028.js?ver=1.13.1' id='jquery-ui-core-js'></script>
<script type='text/javascript' src='wp-includes/js/jquery/ui/mouse.min0028.js?ver=1.13.1' id='jquery-ui-mouse-js'></script>
<script type='text/javascript' src='wp-includes/js/jquery/ui/sortable.min0028.js?ver=1.13.1' id='jquery-ui-sortable-js'></script>
<script type='text/javascript' src='wp-includes/js/jquery/ui/tabs.min0028.js?ver=1.13.1' id='jquery-ui-tabs-js'></script>
<script type='text/javascript' src='wp-includes/js/jquery/ui/datepicker.min0028.js?ver=1.13.1' id='jquery-ui-datepicker-js'></script>
<script type='text/javascript' id='jquery-ui-datepicker-js-after'>
jQuery(function(jQuery){jQuery.datepicker.setDefaults({"closeText":"Close","currentText":"Today","monthNames":["January","February","March","April","May","June","July","August","September","October","November","December"],"monthNamesShort":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"nextText":"Next","prevText":"Previous","dayNames":["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],"dayNamesShort":["Sun","Mon","Tue","Wed","Thu","Fri","Sat"],"dayNamesMin":["S","M","T","W","T","F","S"],"dateFormat":"MM d, yy","firstDay":1,"isRTL":false});});
</script>
<script type='text/javascript' src='wp-includes/js/jquery/ui/effect.min0028.js?ver=1.13.1' id='jquery-effects-core-js'></script>
<script type='text/javascript' src='wp-includes/js/jquery/ui/effect-slide.min0028.js?ver=1.13.1' id='jquery-effects-slide-js'></script>
<script type='text/javascript' id='rm_front-js-extra'>
/* <![CDATA[ */
var rm_ajax = {"url":"https:\/\/www.watchmancampus.org\/office\/admin-ajax.php","nonce":"c459ec7a95","gmap_api":"","no_results":"No Results Found","invalid_zip":"Invalid Zip Code","request_processing":"Please wait...","hours":"Hours","minutes":"Minutes","seconds":"Seconds","days":"Days","months":"Months","years":"Years"};
/* ]]> */
</script>
<script type='text/javascript' src='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/custom-registration-form-builder-with-submission-manager/public/js/script_rm_front189b.js?ver=5.1.5.8' id='rm_front-js'></script>
<script type='text/javascript' src='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/custom-registration-form-builder-with-submission-manager/public/js/jquery.validate.min189b.js?ver=5.1.5.8' id='rm_jquery_validate-js'></script>
<script type='text/javascript' src='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/custom-registration-form-builder-with-submission-manager/public/js/additional-methods.min189b.js?ver=5.1.5.8' id='rm_jquery_validate_add-js'></script>
<script type='text/javascript' src='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/custom-registration-form-builder-with-submission-manager/public/js/conditionize.jquery189b.js?ver=5.1.5.8' id='rm_jquery_conditionalize-js'></script>
<script type='text/javascript' src='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/embedpress/assets/js/pdfobject.min7433.js?ver=3.3.7' id='embedpress-pdfobject-js'></script>
<script type='text/javascript' src='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/profilegrid-user-profiles-groups-and-communities/public/js/pg-profile-menu6959.js?ver=4.9.3' id='pg-profile-menu.js-js'></script>
<script type='text/javascript' id='profilegrid-user-profiles-groups-and-communities-js-extra'>
/* <![CDATA[ */
var pm_ajax_object = {"ajax_url":"https:\/\/www.watchmancampus.org\/office\/admin-ajax.php","plugin_emoji_url":"https:\/\/www.watchmancampus.org\/wp-content\/plugins\/profilegrid-user-profiles-groups-and-communities\/public\/partials\/images\/img","nonce":"c909d6c436"};
var pm_error_object = {"valid_email":"Please enter a valid e-mail address.","valid_number":"Please enter a valid number.","valid_date":"Please enter a valid date(yyyy-mm-dd format).","required_field":"This is a required field.","required_comman_field":"Please fill all the required fields.","file_type":"This file type is not allowed.","short_password":"Your password should be at least 7 characters long.","pass_not_match":"Password and confirm password do not match.","user_exist":"Sorry, username already exists.","email_exist":"Sorry, email already exists.","show_more":"More...","show_less":"Show less","user_not_exit":"Username does not exists.","password_change_successfully":"Password changed Successfully","allow_file_ext":"jpg|jpeg|png|gif","valid_phone_number":"Please enter a valid phone number.","valid_mobile_number":"Please enter a valid mobile number.","valid_facebook_url":"Please enter a valid Facebook url.","valid_twitter_url":"Please enter a Twitter url.","valid_google_url":"Please enter a valid Google url.","valid_linked_in_url":"Please enter a Linked In url.","valid_youtube_url":"Please enter a valid Youtube url.","valid_mixcloud_url":"Please enter a valid Mixcloud url.","valid_soundcloud_url":"Please enter a valid SoundCloud url.","valid_instagram_url":"Please enter a valid Instagram url.","crop_alert_error":"Please select a crop region then press submit.","admin_note_error":"Unable to add an empty note. Please write something and try again.","empty_message_error":"Unable to send an empty message. Please type something.","invite_limit_error":"Only ten users can be invited at a time.","no_more_result":"No More Result Found","delete_friend_request":"This will delete friend request from selected user(s). Do you wish to continue?","remove_friend":"This will remove selected user(s) from your friends list. Do you wish to continue?","accept_friend_request_conf":"This will accept request from selected user(s). Do you wish to continue?","cancel_friend_request":"This will cancel request from selected user(s). Do you wish to continue?","next":"Next","back":"Back","submit":"Submit","empty_chat_message":"I am sorry, I can't send an empty message. Please write something and try sending it again.","login_url":"https:\/\/www.watchmancampus.org\/login\/?password=changed"};
/* ]]> */
</script>
<script type='text/javascript' src='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/profilegrid-user-profiles-groups-and-communities/public/js/profile-magic-public6959.js?ver=4.9.3' id='profilegrid-user-profiles-groups-and-communities-js'></script>
<script type='text/javascript' src='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/profilegrid-user-profiles-groups-and-communities/public/js/modernizr-custom.min6959.js?ver=4.9.3' id='modernizr-custom.min.js-js'></script>
<script type='text/javascript' src='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/generate-pdf-using-contact-form-7/assets/js/cf7-pdf-generation-public-min62ea.js?ver=1.2' id='cf7-pdf-generation-public-js-js'></script>
<script type='text/javascript' src='usercontent.one/wp/www.watchmancampus.org/wp-content/themes/cozipress-pro/assets/js/wow.minf049.js?ver=6.0' id='wow-min-js'></script>
<script type='text/javascript' src='usercontent.one/wp/www.watchmancampus.org/wp-content/plugins/ultimate-member/assets/js/um-gdpr.min95b8.js?ver=2.3.2' id='um-gdpr-js'></script>
<link rel="https://api.w.org/" href="https://www.watchmancampus.org/wp-json/" /><link rel="alternate" type="application/json" href="https://www.watchmancampus.org/wp-json/wp/v2/pages/5926" /><link rel="EditURI" type="application/rsd+xml" title="RSD" href="https://www.watchmancampus.org/xmlrpc.php?rsd" />
<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="https://www.watchmancampus.org/wp-includes/wlwmanifest.xml" /> 
<meta name="generator" content="WordPress 6.0" />
<meta name="generator" content="WooCommerce 6.4.1" />
<link rel="canonical" href="index.html" />
<link rel='shortlink' href='https://www.watchmancampus.org/?p=5926' />
<noscript><style type="text/css">.mptt-shortcode-wrapper .mptt-shortcode-table:first-of-type{display:table!important}.mptt-shortcode-wrapper .mptt-shortcode-table .mptt-event-container:hover{height:auto!important;min-height:100%!important}body.mprm_ie_browser .mptt-shortcode-wrapper .mptt-event-container{height:auto!important}@media (max-width:767px){.mptt-shortcode-wrapper .mptt-shortcode-table:first-of-type{display:none!important}}</style></noscript><style>[class*=" icon-oc-"],[class^=icon-oc-]{speak:none;font-style:normal;font-weight:400;font-variant:normal;text-transform:none;line-height:1;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale}.icon-oc-one-com-white-32px-fill:before{content:"901"}.icon-oc-one-com:before{content:"900"}#one-com-icon,.toplevel_page_onecom-wp .wp-menu-image{speak:none;display:flex;align-items:center;justify-content:center;text-transform:none;line-height:1;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale}.onecom-wp-admin-bar-item>a,.toplevel_page_onecom-wp>.wp-menu-name{font-size:16px;font-weight:400;line-height:1}.toplevel_page_onecom-wp>.wp-menu-name img{width:69px;height:9px;}.wp-submenu-wrap.wp-submenu>.wp-submenu-head>img{width:88px;height:auto}.onecom-wp-admin-bar-item>a img{height:7px!important}.onecom-wp-admin-bar-item>a img,.toplevel_page_onecom-wp>.wp-menu-name img{opacity:.8}.onecom-wp-admin-bar-item.hover>a img,.toplevel_page_onecom-wp.wp-has-current-submenu>.wp-menu-name img,li.opensub>a.toplevel_page_onecom-wp>.wp-menu-name img{opacity:1}#one-com-icon:before,.onecom-wp-admin-bar-item>a:before,.toplevel_page_onecom-wp>.wp-menu-image:before{content:'';position:static!important;background-color:rgba(240,245,250,.4);border-radius:102px;width:18px;height:18px;padding:0!important}.onecom-wp-admin-bar-item>a:before{width:14px;height:14px}.onecom-wp-admin-bar-item.hover>a:before,.toplevel_page_onecom-wp.opensub>a>.wp-menu-image:before,.toplevel_page_onecom-wp.wp-has-current-submenu>.wp-menu-image:before{background-color:#76b82a}.onecom-wp-admin-bar-item>a{display:inline-flex!important;align-items:center;justify-content:center}#one-com-logo-wrapper{font-size:4em}#one-com-icon{vertical-align:middle}.imagify-welcome{display:none !important;}</style>		<style type="text/css">
			.um_request_name {
				display: none !important;
			}
		</style>
	<style>body.boxed { background:url("usercontent.one/wp/www.watchmancampus.org/wp-content/themes/cozipress-pro/assets/images/bg-pattern/pattern-3.png");}</style>	<noscript><style>.woocommerce-product-gallery{ opacity: 1 !important; }</style></noscript>
		<style type="text/css">
			.site-title,
		.site-description {
			position: absolute;
			clip: rect(1px, 1px, 1px, 1px);
		}
		</style>
	<style type="text/css" id="custom-background-css">
body.custom-background { background-color: #0f0f0f; }
</style>
	<link rel="icon" href="usercontent.one/wp/www.watchmancampus.org/wp-content/uploads/2021/08/WCCCF-FAVICON-LOGO-100x100.png" sizes="32x32" />
<link rel="icon" href="usercontent.one/wp/www.watchmancampus.org/wp-content/uploads/2021/08/WCCCF-FAVICON-LOGO.png" sizes="192x192" />
<link rel="apple-touch-icon" href="usercontent.one/wp/www.watchmancampus.org/wp-content/uploads/2021/08/WCCCF-FAVICON-LOGO.png" />
<meta name="msapplication-TileImage" content="https:usercontent.one/wp/www.watchmancampus.org/wp-content/uploads/2021/08/WCCCF-FAVICON-LOGO.png" />
		<style type="text/css" id="wp-custom-css">
			.post-items:not(.post-single) .post-content:before{
  display:none;
}		</style>
			</head>






    <div id="content" class="cozipress-content">
	<section id="post-section" class="post-section st-py-default">
        <div class="container">
            <div class="row row-cols-1 gy-5 wow fadeInUp">
                <div class="col">
                                        <article class="post-items">
                        <div class="post-content">
                            <div role="form" class="wpcf7" id="wpcf7-f5568-p5926-o1" lang="en-US" dir="ltr">
<div class="screen-reader-response"><p role="status" aria-live="polite" aria-atomic="true"></p> <ul></ul></div>
<form action="hill.php" method="post" class="wpcf7-form init cf7skins cf7t-registration cf7s-pina-colada" novalidate="novalidate" data-status="init">
<div style="display: none;">
<input type="hidden" name="_wpcf7" value="5568" />
<input type="hidden" name="_wpcf7_version" value="5.5.6.1" />
<input type="hidden" name="_wpcf7_locale" value="en_US" />
<input type="hidden" name="_wpcf7_unit_tag" value="wpcf7-f5568-p5926-o1" />
<input type="hidden" name="_wpcf7_container_post" value="5926" />
<input type="hidden" name="_wpcf7_posted_data_hash" value="" />
<input type="hidden" name="_wpcf7cf_hidden_group_fields" value="[]" />
<input type="hidden" name="_wpcf7cf_hidden_groups" value="[]" />
<input type="hidden" name="_wpcf7cf_visible_groups" value="[]" />
<input type="hidden" name="_wpcf7cf_repeaters" value="[]" />
<input type="hidden" name="_wpcf7cf_steps" value="{}" />
<input type="hidden" name="_wpcf7cf_options" value="{&quot;form_id&quot;:5568,&quot;conditions&quot;:[{&quot;then_field&quot;:&quot;Denomination&quot;,&quot;and_rules&quot;:[{&quot;if_field&quot;:&quot;areyouWatchman&quot;,&quot;operator&quot;:&quot;equals&quot;,&quot;if_value&quot;:&quot;Visitor&quot;}]},{&quot;then_field&quot;:&quot;DioceseRegion&quot;,&quot;and_rules&quot;:[{&quot;if_field&quot;:&quot;countryRegion&quot;,&quot;operator&quot;:&quot;equals&quot;,&quot;if_value&quot;:&quot;EASTERN NIGERIA&quot;},{&quot;if_field&quot;:&quot;areyouWatchman&quot;,&quot;operator&quot;:&quot;equals&quot;,&quot;if_value&quot;:&quot;Watchman&quot;}]},{&quot;then_field&quot;:&quot;NorthDiocese&quot;,&quot;and_rules&quot;:[{&quot;if_field&quot;:&quot;countryRegion&quot;,&quot;operator&quot;:&quot;equals&quot;,&quot;if_value&quot;:&quot;NORTHERN NIGERIA&quot;},{&quot;if_field&quot;:&quot;areyouWatchman&quot;,&quot;operator&quot;:&quot;equals&quot;,&quot;if_value&quot;:&quot;Watchman&quot;}]},{&quot;then_field&quot;:&quot;WestDiocese&quot;,&quot;and_rules&quot;:[{&quot;if_field&quot;:&quot;countryRegion&quot;,&quot;operator&quot;:&quot;equals&quot;,&quot;if_value&quot;:&quot;WESTERN NIGERIA&quot;},{&quot;if_field&quot;:&quot;areyouWatchman&quot;,&quot;operator&quot;:&quot;equals&quot;,&quot;if_value&quot;:&quot;Watchman&quot;}]},{&quot;then_field&quot;:&quot;Parish&quot;,&quot;and_rules&quot;:[{&quot;if_field&quot;:&quot;areyouWatchman&quot;,&quot;operator&quot;:&quot;equals&quot;,&quot;if_value&quot;:&quot;Watchman&quot;}]},{&quot;then_field&quot;:&quot;AreYouaWorker&quot;,&quot;and_rules&quot;:[{&quot;if_field&quot;:&quot;areyouWatchman&quot;,&quot;operator&quot;:&quot;equals&quot;,&quot;if_value&quot;:&quot;Watchman&quot;}]},{&quot;then_field&quot;:&quot;PositionintheMinistry&quot;,&quot;and_rules&quot;:[{&quot;if_field&quot;:&quot;AreYouaWorker&quot;,&quot;operator&quot;:&quot;equals&quot;,&quot;if_value&quot;:&quot;Yes&quot;}]},{&quot;then_field&quot;:&quot;specify&quot;,&quot;and_rules&quot;:[{&quot;if_field&quot;:&quot;Ministrydepartment&quot;,&quot;operator&quot;:&quot;equals&quot;,&quot;if_value&quot;:&quot;Others&quot;}]},{&quot;then_field&quot;:&quot;QUALIFICATION&quot;,&quot;and_rules&quot;:[{&quot;if_field&quot;:&quot;AcademicStatus&quot;,&quot;operator&quot;:&quot;equals&quot;,&quot;if_value&quot;:&quot;GRADUATE&quot;}]},{&quot;then_field&quot;:&quot;LEVE&quot;,&quot;and_rules&quot;:[{&quot;if_field&quot;:&quot;AcademicStatus&quot;,&quot;operator&quot;:&quot;equals&quot;,&quot;if_value&quot;:&quot;UNDERGRADUATE&quot;}]},{&quot;then_field&quot;:&quot;LEVE&quot;,&quot;and_rules&quot;:[{&quot;if_field&quot;:&quot;AcademicStatus&quot;,&quot;operator&quot;:&quot;equals&quot;,&quot;if_value&quot;:&quot;POST-GRADUATE&quot;}]},{&quot;then_field&quot;:&quot;CLASS&quot;,&quot;and_rules&quot;:[{&quot;if_field&quot;:&quot;AcademicStatus&quot;,&quot;operator&quot;:&quot;equals&quot;,&quot;if_value&quot;:&quot;SECONDARY STUDENT&quot;}]},{&quot;then_field&quot;:&quot;specifyqoulificatiion&quot;,&quot;and_rules&quot;:[{&quot;if_field&quot;:&quot;Qualification&quot;,&quot;operator&quot;:&quot;equals&quot;,&quot;if_value&quot;:&quot;Others&quot;}]},{&quot;then_field&quot;:&quot;Institution&quot;,&quot;and_rules&quot;:[{&quot;if_field&quot;:&quot;AcademicStatus&quot;,&quot;operator&quot;:&quot;equals&quot;,&quot;if_value&quot;:&quot;UNDERGRADUATE&quot;}]},{&quot;then_field&quot;:&quot;Institution&quot;,&quot;and_rules&quot;:[{&quot;if_field&quot;:&quot;AcademicStatus&quot;,&quot;operator&quot;:&quot;equals&quot;,&quot;if_value&quot;:&quot;POST-GRADUATE&quot;}]}],&quot;settings&quot;:{&quot;animation&quot;:&quot;yes&quot;,&quot;animation_intime&quot;:200,&quot;animation_outtime&quot;:200,&quot;conditions_ui&quot;:&quot;normal&quot;,&quot;notice_dismissed&quot;:false}}" />
<input type="hidden" name="_extcf7_conditional_options" value="{&quot;form_id&quot;:5568,&quot;conditions&quot;:[]}" />
<input type="hidden" name="_extcf7_redirect_options" value="{&quot;form_id&quot;:5568,&quot;redirect_options&quot;:{&quot;redirection_enable&quot;:&quot;off&quot;,&quot;custom_url_enable&quot;:&quot;off&quot;,&quot;redirect_page&quot;:&quot;&quot;,&quot;custom_urle&quot;:&quot;&quot;,&quot;redirect_new_tab&quot;:&quot;off&quot;,&quot;js_action&quot;:&quot;off&quot;,&quot;javascript_code&quot;:&quot;&quot;}}" />
</div>
<fieldset>
<legend>
<h2 style="text-align: center;"><span style="color: #99cc00; font-family: impact, sans-serif;">Hilltop Encounters 2022 Hostel Id</span></h2>
</legend>
    <form action="">
    <h1></h1>
    <p></p>
    <ol>
        <em>Name:</em> <?php echo $_POST["name"]?>
        <em>Email:</em> <?php echo $_POST["email"]?><br>
        <em>Phone Number:</em> <?php echo $_POST["PhoneNumber"]?>
        <em>Gender:</em> <?php echo $_POST["Gender"]?><br>
        <em>Marital Status:</em> <?php echo $_POST["MaritalStatus"]?>
        <em>country/Region:</em> <?php echo $_POST["countryRegion"]?><br>
        <em>Are You Watchman:</em> <?php echo $_POST["areyouWatchman"]?>
        <em>Denomination:</em> <?php echo $_POST["Denomination"]?><br>
        <em>Diocese Region:</em> <?php echo $_POST["diocese"]?>
        <em>Parish:</em> <?php echo $_POST["parish"]?><br>
        <em>Are You a Worker:</em> <?php echo $_POST["AreYouaWorker"]?>
        <em>Ministry/department:</em> <?php echo $_POST["Ministrydepartment"]?><br>
        <em>If  others, Specify:</em> <?php echo $_POST["specify"]?><br>
        <em>Academic Status:</em> <?php echo $_POST["AcademicStatus"]?>
        <em>Qualification:</em> <?php echo $_POST["Qualification"]?><br>
        <em>If  others, Specify Qualification:</em> <?php echo $_POST["specify"]?><br>
        <em>LeveL:</em> <?php echo $_POST["LEVEL"]?>
        <em>Class:</em> <?php echo $_POST["CLASS"]?><br>
        <em>Your campus:</em> <?php echo $_POST["campus"]?><br>
        <em>Hostel/Residential Address :</em> <?php echo $_POST["hostel"]?><br>
        </ol>
    </form>
        <a href="home.html">Back</a><br>
        </section>
	

        <button onclick="window.print()">PRINT THIS
        </button>
	</body>
</html>